export const PAGE_HEADER_CLASS = 'page-header'
export const PAGE_CONTENT_CLASS = 'page-content'
export const PAGE_FRAME_CLASS = 'page-frame'
export const PAGE_DASHBOARD_FRAME_CLASS = 'page-frame page-frame-dashboard'
export const PAGE_WIDE_FRAME_CLASS = 'page-frame page-frame-wide'
export const PAGE_FORM_FRAME_CLASS = 'page-frame page-frame-form'
export const PAGE_READING_FRAME_CLASS = 'page-frame page-frame-reading'
export const ADAPTIVE_NOTE_GRID_CLASS = 'adaptive-note-grid'
